[project]
name = 'Endangered-Species-Genome-Bank'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.compute-network]
path = 'contracts/compute-network.clar'
clarity_version = 2
epoch = 2.5

[contracts.genome-nft]
path = 'contracts/genome-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.wildlife-tracking]
path = 'contracts/wildlife-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
